"""Pydantic models for domain agents.

Defines request/response models for:
- AI Watchlist agent (themed stock watchlist construction)
- Portfolio Builder agent (two-phase intake: clarify → build)
"""

from typing import List

from pydantic import BaseModel, Field


# ================================
# --> Watchlist models
# ================================

class WatchlistItem(BaseModel):
    """A single ticker recommendation in the watchlist."""

    ticker: str = Field(..., description="Stock or ETF ticker symbol")
    name: str = Field(..., description="Full name of the security")
    investment_thesis: str = Field(
        ..., description="Extremely detailed investment thesis for the ticker"
    )


class WatchlistResponse(BaseModel):
    """Complete AI watchlist response containing recommended tickers."""

    investment_thesis: str = Field(
        ..., description="Extremely detailed overall investment thesis for the watchlist theme"
    )
    watchlist: List[WatchlistItem] = Field(
        ..., description="List of recommended tickers"
    )


# ================================
# --> Clarification models
# ================================

class ClarifyingQuestion(BaseModel):
    """A single clarifying question generated by the LLM."""

    id: str = Field(..., description="Question identifier, e.g. 'q1', 'q2'")
    question: str = Field(..., description="Display text for the question")
    category: str = Field(
        ...,
        description="Dimension being clarified: drawdown_tolerance, concentration, "
        "time_horizon, income_needs, factor_tilts, instruments, "
        "position_constraints, benchmark, existing_holdings, capital, "
        "conviction_style",
    )


class ClarificationResponse(BaseModel):
    """Structured output returned by the clarification LLM call."""

    questions: List[ClarifyingQuestion] = Field(
        ..., description="3-8 clarifying questions"
    )
    detected_preferences: List[str] = Field(
        default_factory=list,
        description="Preferences already expressed in the user's query",
    )


class ClarifyRequest(BaseModel):
    """Request body for POST /api/agents/clarify."""

    user_preferences: str = Field(..., description="Raw user query")


class ClarifyResult(BaseModel):
    """Response body for POST /api/agents/clarify."""

    questions: List[ClarifyingQuestion]
    detected_preferences: List[str]
    original_query: str


class ClarifyAnswer(BaseModel):
    """A single user answer to a clarifying question."""

    question_id: str = Field(..., description="Matches ClarifyingQuestion.id")
    question: str = Field(..., description="Original question text for context")
    answer: str = Field(..., description="User's answer text")


class BuildRequest(BaseModel):
    """Request body for POST /api/agents/build-portfolio."""

    user_preferences: str = Field(..., description="Original user query")
    answers: List[ClarifyAnswer] = Field(
        default_factory=list,
        description="Answered clarifying questions. Empty list = skip clarification.",
    )


# ================================
# --> Portfolio output models
# ================================

class PortfolioPosition(BaseModel):
    """A single position in the constructed portfolio."""

    ticker: str = Field(..., description="Ticker symbol")
    allocation: str = Field(..., description="Target allocation, e.g. '15%'")
    direction: str = Field(..., description="Position direction: long or short")
    instrument_type: str = Field(
        ..., description="Instrument: equity, etf, option, etc."
    )
    reasoning: str = Field(
        ..., description="In-depth reasoning behind this position"
    )


class PortfolioResponse(BaseModel):
    """Structured output from the PortfolioBuilder agent."""

    thesis: str = Field(
        ...,
        description="Investment thesis — macro reasoning, strategy rationale, and portfolio narrative",
    )
    portfolio: List[PortfolioPosition] = Field(
        ..., description="Portfolio holdings with per-position reasoning"
    )
