from app.core.atlas.tools.data import (
    EQUITY_SCREENER_TOOL,
    ETF_SCREENER_TOOL,
    GET_SECTOR_PERFORMANCE_TOOL,
    GET_SECTOR_PE_TOOL,
    GET_INDUSTRY_FACTOR_BENCHMARK_TOOL,
    GET_SUB_INDUSTRY_FACTOR_BENCHMARK_TOOL,
    GET_TICKER_FUNDAMENTAL_DATA_TOOL,
    GET_RATIOS_TTM_TOOL,
    GET_PRODUCT_SEGMENTATION_TOOL,
    GET_TICKER_PEERS_TOOL,
    GET_TICKER_INFO_TOOL,
)
from app.core.atlas.tools.ticker import (
    GET_TICKER_PERFORMANCE_AND_RISK_TOOL,
    CALCULATE_TICKER_FACTORS_TOOL,
)

def register_ai_watchlist_tools(agent):
    agent.add_tool(**EQUITY_SCREENER_TOOL)
    agent.add_tool(**ETF_SCREENER_TOOL)
    agent.add_tool(**GET_SECTOR_PERFORMANCE_TOOL)
    agent.add_tool(**GET_SECTOR_PE_TOOL)
    agent.add_tool(**GET_INDUSTRY_FACTOR_BENCHMARK_TOOL)
    agent.add_tool(**GET_SUB_INDUSTRY_FACTOR_BENCHMARK_TOOL)
    agent.add_tool(**GET_TICKER_PERFORMANCE_AND_RISK_TOOL)
    agent.add_tool(**CALCULATE_TICKER_FACTORS_TOOL)
    agent.add_tool(**GET_TICKER_FUNDAMENTAL_DATA_TOOL)
    agent.add_tool(**GET_RATIOS_TTM_TOOL)
    agent.add_tool(**GET_PRODUCT_SEGMENTATION_TOOL)
    agent.add_tool(**GET_TICKER_PEERS_TOOL)
    agent.add_tool(**GET_TICKER_INFO_TOOL)